### ISSUE TITLE
Bug con l'ultima vita disponibile

### ISSUE THREAD

**Issue by rockbreaker94** [puzza/CanvasGames#1]
Buongiorno,
andando avanti con il gioco, perdendo tutte le vite tranne l'ultima, ho schiacciato involontariamente il tasto del mouse. Nonostante non avessi perso l'ultima vita, ha ricominciato da capo ricaricandomi le vite.
Allego videate.

Mirko 1
![vite_quasi_finite](https://user-images.githubusercontent.com/7248664/35680284-32327bc0-075a-11e8-83fb-7d4fde9a5871.png)
![vite_ricaricate](https://user-images.githubusercontent.com/7248664/35680288-33da772a-075a-11e8-8027-6a6e8a7757a3.png)

**Comment by puzza** [comment]
Buongiorno gentile cliente,
la sua segnalazione è risolta con la versione 0.2
Le auguriamo una nuova e corroborante esperienza di gioco!
Giorgio.
